backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "contents"
    label: "Pages"
    files:
      - file: "src/contents/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "index-page",
          }
          - { label: Title, name: title, widget: string }
          - { label: Banner image, name: bannerImage, widget: image }
          - { label: Banner strong text, name: bannerStrongText, widget: string }
          - { label: Banner text, name: bannerText, widget: string }